### ISSUE TITLE
deck finish patch by kitchen door still visible

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#163]
looks better than before but the patch that was sanded is still visible

**Comment by delcontejeff** [comment]
Hi Ben,

Spoke to the painter, this was the  best approach to fix the scratch as the sealer is clear, without stain color, the patch will eventually fade/darken to the existing color as the rest of the deck, unfortunately its right in front of the door. Adding a stain, in the long run would look worse.

I spoke to Tom of ICON, re : breakers, he knows what the problem is and was expected to send you an email with a more detailed explanation this past weekend and to provide solutions to solve the issues. 

I was unable to get to tightening the door escutcheons last week, will get to it today or tomorrow.

Jeff
