### ISSUE TITLE
Tv setup in master bed/bath

### ISSUE THREAD

**Issue by bengoodger** [bengoodger/ranchtastic#88]
two screens (mbed/bath) driven from:
- tivo mini
- bluray player
- chromecast

in closet.

**Comment by delcontejeff** [comment]
Mike has found a solution he can recommend, knows you do not need an amp., but the switching and connectivity aspect is required. rather than getting an "unknown" HDMI switcher, Mike says he has an "integra" , DTR, receiver that is new /refurbished you can get for 1/2 Off cost ~$500 to do all you need and reliable.
